version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"  # Expose Laravel app to host on port 8000
    volumes:
      - .:/var/www/html  # Mount project files inside container
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    command: >
      sh -c "
        until nc -z mysql 3306; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done;
        composer install &&
        php artisan config:clear &&
        php artisan key:generate &&
        php artisan migrate:fresh &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"  # Expose MySQL to host on port 3307
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
